### ISSUE TITLE
Maritime Trade Legacy seems broken

### ISSUE THREAD

**Issue by crustybatteryacid** [cybrxkhan/RICE-for-CK3#3]
Hey it's me, the guy who raised a similar complaint on steam a while ago. I figured I could better describe the problem on GitHub.
Anyhow, I started a new game (without the mod that I suspected of breaking things) and it still seems broken.

![image](https://user-images.githubusercontent.com/65634918/115737181-31221c00-a38c-11eb-82ec-fe852fa26e09.png)
Umayyads holding no land outside of Iberia and Northern Africa with the legacy.

![image](https://user-images.githubusercontent.com/65634918/115737263-426b2880-a38c-11eb-9cfe-a5d289a8c105.png)
Random Russian dynasty in Moldova

![image](https://user-images.githubusercontent.com/65634918/115737449-6fb7d680-a38c-11eb-89d4-8c5a352a91d5.png)
Random Polish dynasty in Poland

I do figure it may be caused by mods not being compatible. Here is a full list of mods I play with.
https://steamcommunity.com/sharedfiles/filedetails/?id=2454326101
This is relevant because not a single one of these mods changes anything about dynasty legacies (as far as I know anyway.)

**Comment by crustybatteryacid** [comment]
A few random Siberian tribes too.

**Comment by cybrxkhan** [comment]
Hmm... I wonder if one of the other mods modifies the geographical regions in some way, because one of the triggers for this is region based.

Okay, let's try this to start off with - can you unsubscribe, wait a bit, and then resubscribe to the mod (to make sure it's clean) and then try loading into the game with no other mods except RICE? If the issue still persists then we'll know for sure it's something to do with RICE (or at least your copy of RICE), if there's no issue then we'll know it's probably not RICE in and of itself and this might be due to some wonkiness with some other mod. Either way, can you then check the error log and show me what it says?

Thanks for the patience and help!

**Comment by crustybatteryacid** [comment]
![image](https://user-images.githubusercontent.com/65634918/115936987-01136f80-a497-11eb-9e26-7409de393b73.png)
random Tibetan tribe

![image](https://user-images.githubusercontent.com/65634918/115937038-243e1f00-a497-11eb-8861-e260ef0ba4a6.png)
Bidaic tribe in West Africa

![image](https://user-images.githubusercontent.com/65634918/115937086-40da5700-a497-11eb-897b-344fa81004fe.png)
Slovien Moravia

![image](https://user-images.githubusercontent.com/65634918/115937156-74b57c80-a497-11eb-89a2-2e6a41513e52.png)
House Arpad of Hungary

![image](https://user-images.githubusercontent.com/65634918/115937189-8eef5a80-a497-11eb-886e-e423b95f04a4.png)
Khwarezmians in Uzbekistan

Could probably find more if I tried but I think this proves my point.

I did a full clean installation (game and mod), made a new savegame, and I'm running no mods other than RICE.

Not sure how to access the error log as I am not even remotely experienced with modding. I only help. :D

**Comment by crustybatteryacid** [comment]
Might be worth mentioning that they seem really well spread. Rare but omnipresent.

**Comment by cybrxkhan** [comment]
Hmm... if it's rare then that might be why I missed it, since if it is indeed not something on your end, I may have just coincidentally not selected any dynasties with that issue when testing earlier.

I also thought it over and I think I have an idea as to why it might be happening, but I'd like to see if your error log shows anything relevant first. The error log is located in Documents/Paradox Interactive/Crusader Kings III/logs and should be some kind of text file called "error.log" - do note it changes as you play the game, so I would suggest skipping around to several different rulers first and then playing for a year or two just so we have some data. Hopefully then we can figure this out! Thanks again for the help!

**Comment by cybrxkhan** [comment]
Ok so I've been able to reproduce it at last - your mention that it is rare made me curious so I loaded up an existing save (about 30 years in) and spent 10 minutes looking for it when I finally stumbled on a couple dynasties in north Russia with the issue. My error log doesn't show anything related to the issue, but as mentioned I think I know what might fix it (although I'm not 100% sure why it's causing the issue), though I want to see if there's anything relevant in your error log just in case before I try my idea for the fix.

**Comment by crustybatteryacid** [comment]
Alright. Cleared the log, new observer game, only using RICE. Let's go!

![image](https://user-images.githubusercontent.com/65634918/115998569-1ea41e80-a5e8-11eb-9124-1f65f9543e66.png)
off to a good start

![image](https://user-images.githubusercontent.com/65634918/115998581-2d8ad100-a5e8-11eb-8e92-7a2ae802af35.png)
Moravia again

![image](https://user-images.githubusercontent.com/65634918/115998595-3b405680-a5e8-11eb-8c32-f70d46a0be5a.png)
Umayyads again

![image](https://user-images.githubusercontent.com/65634918/115998609-514e1700-a5e8-11eb-8405-e72ed7bc9e1d.png)
Bidaics again

![image](https://user-images.githubusercontent.com/65634918/115998614-5e6b0600-a5e8-11eb-8a9c-f38f8a9e18da.png)
Afrighids again

![image](https://user-images.githubusercontent.com/65634918/115998620-66c34100-a5e8-11eb-9f0a-1a58f4041b8b.png)
Samanids this time

![image](https://user-images.githubusercontent.com/65634918/115998637-75a9f380-a5e8-11eb-9ddd-a8d118f5798d.png)
different Tibetan tribes

![image](https://user-images.githubusercontent.com/65634918/115998655-9c682a00-a5e8-11eb-9b37-ac40b14094db.png)
Siberian tribes

Should be a decent sample size. Seems to be some (but not all!) of the ones I had last time.

Savegame and error log are attached.
[test.zip](https://github.com/cybrxkhan/RICE-for-CK3/files/6372268/test.zip)
[error.log](https://github.com/cybrxkhan/RICE-for-CK3/files/6372271/error.log)

Looks to me that a lot of the error log is related to my game struggling to deal with my previous (modded) savegames, now that the mods are missing. Hope this is not a problem.

**Comment by cybrxkhan** [comment]
Thanks for the error log and test game! I think that helped - there's a number of bugs that I'm already aware of related to other non-critical bugs, but nothing specifically about the Maritime Trade dynasty stuff so it more or less matches what I have with my error log - which is good actually as it confirmed my suspicions that this wasn't something like a typo or a "real" issue like that.

Anyhow, I _think_ I fixed it, and I think the issue was that I had a coded triggers for the dynasty legacies overall, but not the dynasty perks. I uploaded the fixes to GitHub, so if you don't mind, can you test it out by downloading it here (separate from the official release), deleting/unsubscribing from the version of RICE you currently have (to make sure you don't accidentally have the old code around just to be safe), and reinstalling it manually: https://github.com/cybrxkhan/RICE-for-CK3/archive/refs/heads/master.zip

I left the game running for about a century, and then went around for almost 15 minutes through random rulers, and did not find anything weird, and hopefully it's the same for you.

In case you're wondering, the two files I changed were:

RICE/common/dynasty_perks/RICE_socotra_dynasty_perks.txt
RICE/common/scripted_triggers/RICE_scripted_triggers.txt

The first one is the code for the individual perks (as opposed to the legacy as a whole), and the latter is for various special triggers I use in different parts of the mod.

Thanks again for the patience and help, hopefully this fix will work for you - do let me know if it works!

**Comment by crustybatteryacid** [comment]
I would love to check but I can not seem to get the manual installation to work. 
I put extracted folder in my ck3 mod folder and it refuses to show up. :(

**Comment by cybrxkhan** [comment]
:| Hmm, did you make sure both the RICE folder and the .mod file are in the folder? Other thing to make sure is that you're unsubscribed from the Steam workshop version, and you may have to reload the launcher a few times since it's pretty screwy and stupid sometimes.

If that doesn't work, as a last resort, I don't know if it'll work, but make sure you have RICE subscribed on Steam, and then go to the following folder: C:\Program Files (x86)\Steam\steamapps\workshop\content\1158310\2273832430\common

Go into dynasty_perks and scripted_triggers and replace the text files in them with the text files I've attached to this post below, and hopefully Steam will not replace them.

[RICE_socotra_dynasty_perks.txt](https://github.com/cybrxkhan/RICE-for-CK3/files/6402584/RICE_socotra_dynasty_perks.txt)
[RICE_scripted_triggers.txt](https://github.com/cybrxkhan/RICE-for-CK3/files/6402585/RICE_scripted_triggers.txt)

Hope something will work, and thanks again.

**Comment by cybrxkhan** [comment]
Hey there, so I uploaded a new version of the mod, which hopefully will fix the issue - let me know if you still encounter it or not! And thanks again for all your assistance, helping me get to the bottom of this! I honestly wouldn't have noticed it without you.

**Comment by crustybatteryacid** [comment]
Sorry I was away for a few days.

I have not been able to replicate the issue anymore with the new update. I just checked for 10 minutes.

Also I am glad to help. I feel like I owe this much to great modders like you that put in so much work to improve my favourite games.
Besides, I do have a very self-serving interest in having my favourite games be bug-free! :D

Great work! I will let you know in the future, should I encounter anything.

**Comment by cybrxkhan** [comment]
Thank you very much for the help, and glad the issue is gone! Feel free to let me know if you encounter other shenanigans in the future, and thanks again! :)
