### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by mertingen** [cybrxkhan/RICE-for-CK3#68]
Hi @cybrxkhan ,

I'd like to translate English events to Turkish. Because Turkish society is using this workshop a lot and I'd like to provide Turkish translation if it's possible.

**Comment by cybrxkhan** [comment]
Hello! Thank you very much for reaching out to me. I don't know how translation works for languages that are not officially supported, so let me know how it'll work out on your end (for ex would it be a sub-mod that I would need to link to in my description?). You can also reach out to me on discord if that's easier to chat.
Cheers!

**Comment by mertingen** [comment]
I couldn't find your on Discord @cybrxkhan :l

I think I need to create a sub-mod of yours and change localization files from English to Turkish. Is it possible, what do you think?
I mentioned about translating RICE-for-CK3 and Turkish community got happy a lot.

**Comment by cybrxkhan** [comment]
For future reference, in case you still can't find me on discord, you can also try the discord server link here: https://discord.gg/9KuyXv2uZA

Anyways, sub-mod sounds good! I think it would be easier on my end since I don't need to have any direct involvement other than making sure I provide a link to your submod in the RICE description (the Chinese and Korean translators have done something like that in the past, for example).

At any rate, let me know if you have any questions. Hopefully the discord link above works!
