### ISSUE TITLE
Casus Bellis for Normandy

### ISSUE THREAD

**Issue by JediNite** [cybrxkhan/RICE-for-CK3#84]
Hi,

Firstly, I love the work that has gone into this mod.  So very detailed and lots of scenarios. :)

I have just started a playthrough of the Normandy scenario and have found that the Casus Bellis for it, seem to allow any territory on the map to be the target of the Casus Belli.  For example, within the game, I can start an "Invade Kingdom (Normandy Region)" Casus Belli against a Kingdom that could be located in India.  This does not seem to be right. :(

Is it a bug in the "RICE/common/casus_belli_types/RICE_normandy_invasion_cbs.txt" file perhaps ?

Thanks,

JediNite

**Comment by cybrxkhan** [comment]
Hi there!

Thanks for the report! Just quickly checked and I was unable to reproduce the issue, as I can't declare war on someone in India if I'm in Europe because I'm too far away. Do you have other details about what's going on (like who you the potential attacker are and what territories you hold, who the potential defender is, what phase the Normandy struggle is in, etc.), and especially do you have any screenshots you can provide?

Also, have you tried testing it with only RICE running and no other mods, not even other mods that you think are minor and cosmetic?

**Comment by JediNite** [comment]
Hi,

Will see if I have a saved game showing this.  Once I converted to Catholic from Asatru the option to invade so far away disappeared.  It also was just one invasion in the rulers lifetime, so once i did invade one of the kingdoms the option went away.

No other mods in use either.  Just RICE by itself.

JediNite

**Comment by cybrxkhan** [comment]
Sounds good, hopefully you'll have a screenshot or old save lying around that might help us figure out what's going on, thanks!

**Comment by JediNite** [comment]
[King_Tolir_of_Brittany_905_01_19.zip](https://github.com/cybrxkhan/RICE-for-CK3/files/13205770/King_Tolir_of_Brittany_905_01_19.zip)

Hi,

Giver this one a try.  I opened it and found it was not able to attack Kingdoms in India, but was able to attack Hungary with a Casus Belli indicating "Invade Kingdom (Normandy region)".  I'll keep looking for another save.

JediNite

**Comment by cybrxkhan** [comment]
Just loaded into the game but I'm not sure what the issue is, as the CB appears to be working fine and similarly to the normal Invade Kingdom CB available outside the Normandy region at least on my end - I can attack most people in Europe and North Africa in my diplomatic range, and anyone outside that range like in India or the Middle East I can't interact with anyways. Mind posting a screenshot pointing to an example where it's not working like the above? That might help me figure out what the issue is for you specifically.

**Comment by JediNite** [comment]
Thanks for looking into the save file.  I'll have another look and some more of the saves when I got more time and see if I can find one showing the exact issue ( and get some screens). When I quickly checked that one last night saw it come up with the "Too far away" message as well, but thought even Hungary seemed a bit far from Normandy.

**Comment by JediNite** [comment]
Hi,

I had a look at the other save games that I had for this play through and can't see it on any of them.  Maybe it was just a glitch on the game as it was loaded in memory at the time.  Think we just close this issue off, and if I do see it again, will ensure I have a save game and some screenshots to make troubleshooting easier.

Thanks again for taking the time to have a bit of a look.

JediNite

**Comment by cybrxkhan** [comment]
Thank you very much! And no worries, hopefully that will be the last we hear of the issue, but who knows, maybe it's a rare edge case, and don't hesitate to let me know if it appears again. Cheers!
